### ISSUE TITLE
Readme Feedback

### ISSUE THREAD

**Issue by mhrgoldberg** [gisales92/SoundCloudClone#1]
- [x] auth routes are usually special in the fact that they usually don't mention the resource of "Users". Try routes such as "/signup", "/login", "logout", etc...
- [x] Wherever you use :id use a more descriptive variable name such as :userId or :albumId (this is only in a few places in your documentation!)
- [x] Make sure ALL edit routes are method: PUT or PATCH and all delete routes are method: DELETE. Delete routes do not need "/delete" in the route because the method lets us know this. We only need to use the URL when we are creating a traditional serfer which is using vanilla HTML forms to make POST requests to the server. Since we are using the FETCH API we can let the server know what endpoint we want by the method.
- [x] "Get all [Songs, Albums, Playlists] of an Artist from an id" URL should not be nested under "/users" it should be eg: "/artists/:artistId/songs"
- [x] "Add a Song to a Playlist based on the Playlists's id" route should have a "playlists" plural, not "playlist"
- [x] "Add Query Filters to Get All Songs" Don't need to have :params to mark that their are query params in te url

**Comment by gisales92** [comment]
Closing from a while ago
